name: helm reuse workflow

on:
  workflow_dispatch:

jobs:
  helm-reuse:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: helm installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: helm repository checkout
        uses: actions/checkout@v2
        with:
          repository: kuntrapakam/isolate_helm_chart
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: application
      - name: getting location
        run: |
          pwd
          ls -ltrha
      - name: helm package
        run: helm template .
